### ISSUE TITLE
No validation on book/profile updates

### ISSUE THREAD

**Issue by LukeSlev** [CMPUT301W19T09/SkipTheLibrary#56]

**Comment by tymoorej** [comment]
@LukeSlev can you take this on? Or would you like me to?

**Comment by LukeSlev** [comment]
I'll take a gander

**Comment by LukeSlev** [comment]
@tymoorej here's a PR https://github.com/CMPUT301W19T09/SkipTheLibrary/pull/62

**Comment by tymoorej** [comment]
Sweet, thanks!
