### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [CMPUT301W19T09/SkipTheLibrary#61]
Hi @tymoorej @LukeSlev , I'm a graphic designer. I like your project, I want to collaborate by creating a free logo/icon for you. What do you think?

**Comment by tymoorej** [comment]
Hello Zularizal, thank you for the offer. We appreciate your generosity. Unfortunately, this is a group project for a class and we are not allowed to accept outside help. Good luck in your pursuit of graphic design!
